# safelist
branches:
  only:
  - master

dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - py.test tests --doctest-modules --pep8 pycollision  -v --cov pycollision --cov-report term-missing tests
after_success:
  - coveralls
